FROM ubuntu/apache2:2.4-24.04_edge

ENV TZ="Europe/Warsaw"

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime
RUN echo $TZ > /etc/timezone

RUN apt update && apt install -y software-properties-common
RUN apt-get install -y bash
RUN add-apt-repository ppa:ondrej/php
RUN apt update
RUN apt install -y supervisor

RUN apt install -y unzip
RUN apt install -y php8.4-fpm php8.4-cli php8.4-mbstring
#RUN apt install -y php8.4-bcmath
RUN apt install -y libapache2-mod-fcgid

RUN a2enmod proxy proxy_fcgi proxy_http setenvif
RUN a2enconf php8.4-fpm

RUN printf '[Date]\ndate.timezone="%s"\n', $TZ > /etc/php/8.4/fpm/conf.d/timezone.ini
RUN printf '[Date]\ndate.timezone="%s"\n', $TZ > /etc/php/8.4/cli/conf.d/timezone.ini

# Install composer latest version
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php --install-dir=/usr/local/bin --filename=composer
RUN php -r "unlink('composer-setup.php');"

WORKDIR /var/www/movies-recommend.local

EXPOSE 80

RUN service apache2 restart

COPY docker/docker-entrypoint-apache.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-apache.sh"]
